version: "3.6"

services:
    storage-app:
        image: dendriel/npc-data-manager-storage:latest
        command: "java -jar /npc-data-manager-storage.jar"
        restart: always
        ports:
            - 8081:8080
        working_dir: /app
        volumes:
            - /home/ec2-user/.aws:/root/.aws
        environment:
            - MYSQL_DB=the_quest
            - MYSQL_HOST=192.168.15.9
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASS=pass
