server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true

auth:
  service:
    url: ${AUTH_URL:http://localhost:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:npc_data}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:pass}

  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 1024KB
      max-request-size: 1024KB

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: never

resource:
  access:
    expiration: 60
