server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  servlet:
    context-path: ${BASE_PATH:}

service:
  url: "http://localhost:3000"
  auth:
    cookie: "AUCC"

spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:npc_data}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:pass}
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 1024KB
      max-request-size: 1024KB
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: never

resource:
  access:
    expiration: 60

storage:
  bucket:
    name: "storage-npcdatamanager"
